### ISSUE TITLE
Comparison dynamic fusion

### ISSUE THREAD

**Issue by YJonmo** [AljazBozic/NeuralGraph#1]
Hi there,

Thanks for this great work.
I have seen a few implementations of the dynamic fusion on github. 
Could you say which implementation of the dynamic fusion you used for the comparison with NeutralGraph in your paper?
OpenCV 4.5.2 also had the dynamic fusion but it is not working.

Regards,
Yaqub

**Comment by AljazBozic** [comment]
Hi Yaqub,

We used our own re-implementation of DynamicFusion, that is also part of previous works (DeepDeform, Neural Non-rigid Tracking). We plan to release it as well, hopefully soon. I was trying out some available DynamicFusion implementations a while ago, but none of them achieved satisfying performance, maybe there are some recent versions that I'm not aware of.

Best,
Aljaz

**Comment by xiangdonglai** [comment]
> Hi Yaqub,
> 
> We used our own re-implementation of DynamicFusion, that is also part of previous works (DeepDeform, Neural Non-rigid Tracking). We plan to release it as well, hopefully soon. I was trying out some available DynamicFusion implementations a while ago, but none of them achieved satisfying performance, maybe there are some recent versions that I'm not aware of.
> 
> Best, Aljaz

Hi Aljaz,

Thank you a lot for this great work. I am wondering there is a followup on this thread, whether you managed to opensource a public version of (multiview) DynamicFusion?

Best,
Donglai
