### ISSUE TITLE
tracking a keyframe

### ISSUE THREAD

**Issue by maorp** [AljazBozic/NeuralGraph#2]
Hi. first thanks for this amazing work. 
I have a question about tracking. how can i deform a specific key frame (with its mesh topology) to another frame in the sequence or to recreate the consistent coloring in the paper? 
my guess is that i can sample keyframe vertices and deform them using NDGs of other frames (instead of the uniform grid sampling in viz.py)

**Comment by AljazBozic** [comment]
Hi @maorp!

Thank you for your interest! Sorry for the late reply. I just added generation of consistent coloring, as in the paper, to the viz.py. That is how we deform from any frame to frame (in this case from any frame to first frame).

Best,
Aljaz
