### ISSUE TITLE
SDF grid acquisition different in code and in paper

### ISSUE THREAD

**Issue by Steve-Tod** [AljazBozic/NeuralGraph#6]
Hi, thank you for sharing the code, the result looks amazing.

I just have one question, in Section 4, Evaluation on Synthetic data, it is said that the SDF is computed from 4 fixed view depth image.

> To mimic our real data capture setup, we render 4 fixed depth views for every frame of synthetic animation, and generate SDF grids from these 4 views.

However, in the code for SDF grid generation, it seems it's directly computed from mesh without any depth rendering: https://github.com/tomfunkhouser/gaps/blob/f9c51cb706444953c87ed991a2601ffb9173be94/apps/msh2grd/msh2grd.cpp#L74

So does this method require ground truth perfect SDF to train the neural graph?

**Comment by AljazBozic** [comment]
Hi! 

There is an additional step to get a mesh representation, pixel normals are computed from depth maps, and points with normals are backprojected into 3D. Afterwards, a Screened Poisson reconstruction from Meshlab is used to compute a mesh (as described in a paper in sec. 3.1), which can be already quite accurate for synthetic data, but mostly oversmoothed for real data. This mesh is used to generate SDF samples.

An extension of the method that works directly with depth points (basically skipping Poisson preprocessing, which can fail on very partial observations) would be very interesting though. One direction could be by replacing direct SDF loss with an Eikonal loss (as in https://arxiv.org/pdf/2002.10099.pdf). For graph coverage and node interior losses (also described in sec. 3.1), only an approximate visual hull estimate could be enough.

Best,
Aljaz

**Comment by Steve-Tod** [comment]
Got it, thanks!
